apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    purpose: demonstrate-command
spec:
  containers:
    - name: app-container-1
      image: alpine
      command:
        - /bin/sh
        - -c
        - |
          echo $ALPHABET alphabet has $LETTERS_COUNT letters
          i=1
          while [ $i = 1 ]
          do
            sleep 1
            date +"%Y-%m-%d %H:%M:%S"
          done
      env:
      - name: ALPHABET
        value: 'Uganda language'
      - name: LETTERS_COUNT
        value: '18'
      resources:
        limits:
          cpu: 10m
          memory: 10Mi
        requests:
          cpu: 5m
          memory: 5Mi
  terminationGracePeriodSeconds: 1
  restartPolicy: OnFailure