apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: custom-date-logger
    environment: local
  annotations:
    very-clever-developer: "Yevhen Havrasiienko"
    very-clever-developers-github: "https://github.com/llasapg"
spec:
  shareProcessNamespace: true
  containers:
    - name: &container1name app-container-1
      image: alpine
      command:
        - /bin/sh
        - -c
        - |
          i=1
          while [ $i = 1 ]
          do
            sleep 1
            echo [$(CONTAINER_NAME)] && date +"%Y-%m-%d %H:%M:%S"
          done
      env:
        - name: CONTAINER_NAME
          value: *container1name
      resources:
        limits:
          cpu: 10m
          memory: 10Mi
        requests:
          cpu: 5m
          memory: 5Mi
    - name: &container2name app-container-2
      image: alpine
      command:
        - /bin/sh
        - -c
        - |
          echo "some text" >> custom-file.txt
          pwd && ls | grep custom-file.txt
          cat custom-file.txt
          chmod 777 custom-file.txt
          i=1
          while [ $i = 1 ]
          do
            sleep 1
            echo [$(CONTAINER_NAME)] && date +"%Y-%m-%d %H:%M:%S"
          done
      env:
        - name: CONTAINER_NAME
          value: *container2name
      resources:
        limits:
          cpu: 10m
          memory: 10Mi
        requests:
          cpu: 5m
          memory: 5Mi
  initContainers:
    - name: init-container-1
      image: alpine
      command: ["sh", "-c", "date && sleep 1"]
    - name: init-container-2
      image: alpine
      command: ["sh", "-c", "date && sleep 1"]
  terminationGracePeriodSeconds: 1
  restartPolicy: OnFailure